---
title: Sensive Help Guides
timezone: UTC
collections:
  articles:
    title: Articles
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Sensive is a better way to manage your team’s design resources
baseurl: 
permalink: "/:title/"
url: https://help.sensive.co
logo_image:
  light: logo-light.svg
  dark: logo-dark.svg
author:
  name: The Sensive Team
  email: support@sensive.co
  website: 
  facebook: 
  flickr: 
  dribbble: 
  github: 
  googleplus: 
  instagram: 
  linkedin: 
  pinterest: 
  twitter: https://twitter.com/getsensive
  vimeo: 
  youtube: 
twitter_username: 
github_username: 
footer:
  copyright: ©2020 <a href="https://sensive.co/">Sensive LLC</a>
disqus:
  shortname: 
google_analytics: 
google_maps_api_key: 
post_assets: "/assets/posts/"
markdown: kramdown
highlighter: rouge
gems:
- jekyll-feed
- jekyll-seo-tag
- jekyll-gist
exclude:
- Gemfile
- Gemfile.lock
- node_modules
sass:
  style: compressed
